service: rooms
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  logRetentionInDays: 3
  versionFunctions: false

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["rooms", "Arn" ] }
        - { "Fn::GetAtt": ["messages", "Arn" ] }

package:
  patterns:
    - '!./**'
    - './rooms/**'
    - './handler.py'

functions:
  connect:
    handler: handler.connect
    events:
      - websocket: $connect

  disconnect:
    handler: handler.disconnect
    events:
      - websocket: $disconnect

  message:
    handler: handler.message
    events:
      - websocket: $default

plugins:
  - serverless-localstack
  - serverless-python-requirements

custom:
  localstack:
    stages:
      - local
  pythonRequirements:
    noDeploy:
      - boto3
      - botocore
      - jmespath
      - python-dateutil
      - s3transfer
      - six
      - urllib3


resources:
  Resources:
    rooms:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: rooms
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: uid
            AttributeType: S
        KeySchema:
          - AttributeName: uid
            KeyType: HASH
